In [1]:
#imports o
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv("CO2_emission.csv")
print(df.index)
print("All columns are")
ai=0
for i in df:
    print(ai,i)
    ai+=1

RangeIndex(start=0, stop=935, step=1)
All columns are
0 Model_Year
1 Make
2 Model
3 Vehicle_Class
4 Engine_Size
5 Cylinders
6 Transmission
7 Fuel_Consumption_in_City(L/100 km)
8 Fuel_Consumption_in_City_Hwy(L/100 km)
9 Fuel_Consumption_comb(L/100km)
10 CO2_Emissions
11 Smog_Level

In [3]:
df.shape

(935, 12)

In [4]:
df.head

<bound method NDFrame.head of      Model_Year   Make              Model  Vehicle_Class  Engine_Size  \
0          2021  Acura                ILX        Compact          2.4
1          2021  Acura                NSX     Two-seater          3.5
2          2021  Acura         RDX SH-AWD     SUV: Small          2.0
3          2021  Acura  RDX SH-AWD A-SPEC     SUV: Small          2.0
4          2021  Acura         TLX SH-AWD        Compact          2.0
..          ...    ...                ...            ...          ...
930        2021  Volvo        XC40 T5 AWD     SUV: Small          2.0
931        2021  Volvo        XC60 T5 AWD     SUV: Small          2.0
932        2021  Volvo        XC60 T6 AWD     SUV: Small          2.0
933        2021  Volvo        XC90 T5 AWD  SUV: Standard          2.0
934        2021  Volvo        XC90 T6 AWD  SUV: Standard          2.0

     Cylinders Transmission  Fuel_Consumption_in_City(L/100 km)  \
0            4          AM8                                 9.9
1            6          AM9                                11.1
2            4         AS10                                11.0
3            4         AS10                                11.3
4            4         AS10                                11.2
..         ...          ...                                 ...
930          4          AS8                                10.7
931          4          AS8                                11.1
932          4          AS8                                11.7
933          4          AS8                                11.5
934          4          AS8                                12.1

     Fuel_Consumption_in_City_Hwy(L/100 km)  Fuel_Consumption_comb(L/100km)  \
0                                       7.0                             8.6
1                                      10.8                            11.0
2                                       8.6                             9.9
3                                       9.1                            10.3
4                                       8.0                             9.8
..                                      ...                             ...
930                                     7.7                             9.4
931                                     8.3                             9.9
932                                     8.6                            10.3
933                                     8.4                            10.1
934                                     8.5                            10.5

     CO2_Emissions  Smog_Level
0              199           3
1              256           3
2              232           6
3              242           6
4              230           7
..             ...         ...
930            219           5
931            230           5
932            240           7
933            236           5
934            245           7

[935 rows x 12 columns]>

In [5]:
df.sample

<bound method NDFrame.sample of      Model_Year   Make              Model  Vehicle_Class  Engine_Size  \
0          2021  Acura                ILX        Compact          2.4
1          2021  Acura                NSX     Two-seater          3.5
2          2021  Acura         RDX SH-AWD     SUV: Small          2.0
3          2021  Acura  RDX SH-AWD A-SPEC     SUV: Small          2.0
4          2021  Acura         TLX SH-AWD        Compact          2.0
..          ...    ...                ...            ...          ...
930        2021  Volvo        XC40 T5 AWD     SUV: Small          2.0
931        2021  Volvo        XC60 T5 AWD     SUV: Small          2.0
932        2021  Volvo        XC60 T6 AWD     SUV: Small          2.0
933        2021  Volvo        XC90 T5 AWD  SUV: Standard          2.0
934        2021  Volvo        XC90 T6 AWD  SUV: Standard          2.0

     Cylinders Transmission  Fuel_Consumption_in_City(L/100 km)  \
0            4          AM8                                 9.9
1            6          AM9                                11.1
2            4         AS10                                11.0
3            4         AS10                                11.3
4            4         AS10                                11.2
..         ...          ...                                 ...
930          4          AS8                                10.7
931          4          AS8                                11.1
932          4          AS8                                11.7
933          4          AS8                                11.5
934          4          AS8                                12.1

     Fuel_Consumption_in_City_Hwy(L/100 km)  Fuel_Consumption_comb(L/100km)  \
0                                       7.0                             8.6
1                                      10.8                            11.0
2                                       8.6                             9.9
3                                       9.1                            10.3
4                                       8.0                             9.8
..                                      ...                             ...
930                                     7.7                             9.4
931                                     8.3                             9.9
932                                     8.6                            10.3
933                                     8.4                            10.1
934                                     8.5                            10.5

     CO2_Emissions  Smog_Level
0              199           3
1              256           3
2              232           6
3              242           6
4              230           7
..             ...         ...
930            219           5
931            230           5
932            240           7
933            236           5
934            245           7

[935 rows x 12 columns]>

In [6]:
df.info

<bound method DataFrame.info of      Model_Year   Make              Model  Vehicle_Class  Engine_Size  \
0          2021  Acura                ILX        Compact          2.4
1          2021  Acura                NSX     Two-seater          3.5
2          2021  Acura         RDX SH-AWD     SUV: Small          2.0
3          2021  Acura  RDX SH-AWD A-SPEC     SUV: Small          2.0
4          2021  Acura         TLX SH-AWD        Compact          2.0
..          ...    ...                ...            ...          ...
930        2021  Volvo        XC40 T5 AWD     SUV: Small          2.0
931        2021  Volvo        XC60 T5 AWD     SUV: Small          2.0
932        2021  Volvo        XC60 T6 AWD     SUV: Small          2.0
933        2021  Volvo        XC90 T5 AWD  SUV: Standard          2.0
934        2021  Volvo        XC90 T6 AWD  SUV: Standard          2.0

     Cylinders Transmission  Fuel_Consumption_in_City(L/100 km)  \
0            4          AM8                                 9.9
1            6          AM9                                11.1
2            4         AS10                                11.0
3            4         AS10                                11.3
4            4         AS10                                11.2
..         ...          ...                                 ...
930          4          AS8                                10.7
931          4          AS8                                11.1
932          4          AS8                                11.7
933          4          AS8                                11.5
934          4          AS8                                12.1

     Fuel_Consumption_in_City_Hwy(L/100 km)  Fuel_Consumption_comb(L/100km)  \
0                                       7.0                             8.6
1                                      10.8                            11.0
2                                       8.6                             9.9
3                                       9.1                            10.3
4                                       8.0                             9.8
..                                      ...                             ...
930                                     7.7                             9.4
931                                     8.3                             9.9
932                                     8.6                            10.3
933                                     8.4                            10.1
934                                     8.5                            10.5

     CO2_Emissions  Smog_Level
0              199           3
1              256           3
2              232           6
3              242           6
4              230           7
..             ...         ...
930            219           5
931            230           5
932            240           7
933            236           5
934            245           7

[935 rows x 12 columns]>

In [7]:
df.isnull()

,Model_Year,Make,Model,Vehicle_Class,Engine_Size,Cylinders,Transmission,Fuel_Consumption_in_City(L/100 km),Fuel_Consumption_in_City_Hwy(L/100 km),Fuel_Consumption_comb(L/100km),CO2_Emissions,Smog_Level
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
930,False,False,False,False,False,False,False,False,False,False,False,False
931,False,False,False,False,False,False,False,False,False,False,False,False
932,False,False,False,False,False,False,False,False,False,False,False,False
933,False,False,False,False,False,False,False,False,False,False,False,False
934,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
print(df.isnull().sum())
print("The data seems to not have any null values")

Model_Year                                0
Make                                      0
Model                                     0
Vehicle_Class                             0
Engine_Size                               0
Cylinders                                 0
Transmission                              0
Fuel_Consumption_in_City(L/100 km)        0
Fuel_Consumption_in_City_Hwy(L/100 km)    0
Fuel_Consumption_comb(L/100km)            0
CO2_Emissions                             0
Smog_Level                                0
dtype: int64
The data seems to not have any null values

In [14]:
df.describe()

,Model_Year,Engine_Size,Cylinders,Fuel_Consumption_in_City(L/100 km),Fuel_Consumption_in_City_Hwy(L/100 km),Fuel_Consumption_comb(L/100km),CO2_Emissions,Smog_Level
count,935.0,935.000000,935.000000,935.000000,935.000000,935.000000,935.000000,935.000000
mean,2021.0,3.214866,5.716578,12.498610,9.306203,11.060214,258.529412,4.726203
std,0.0,1.388513,1.977359,3.487271,2.215819,2.867028,64.442768,1.712127
min,2021.0,1.000000,3.000000,4.000000,3.900000,4.000000,94.000000,1.000000
25%,2021.0,2.000000,4.000000,10.100000,7.700000,9.100000,213.000000,3.000000
50%,2021.0,3.000000,6.000000,12.000000,9.000000,10.700000,255.000000,5.000000
75%,2021.0,4.000000,8.000000,14.800000,10.800000,13.100000,303.500000,6.000000
max,2021.0,8.000000,16.000000,30.300000,20.900000,26.100000,608.000000,7.000000

In [19]:
print(df.duplicated())
print('Duplicate values :',df.duplicated().sum())

0      False
1      False
2      False
3      False
4      False
       ...
930    False
931    False
932    False
933    False
934    False
Length: 935, dtype: bool
Duplicate values : 0

In [20]:
# now to plot the graphs

ValueError: could not convert string to float: 'Acura'